from pathlib import Path


path = Path("web_ui.py")
text = path.read_text(encoding="utf-8")
text = text.replace("#refresh{margin-left:12px;border:1px solid #9eb1bd;background:#fff;color:#466579;padding:4px 12px;cursor:pointer}#refresh:disabled{opacity:.5;cursor:wait}", "")
text = text.replace("页面每 15 秒自动刷新。<button id='refresh' onclick='manualRefresh()'>立即刷新</button>", "页面打开及每 15 秒自动获取最新邮件。")
text = text.replace(".mail{padding:18px 20px;border-bottom:1px solid #e3eaee}", ".mail{padding:18px 20px;border-bottom:1px solid #e3eaee;cursor:pointer}")

start = text.index("<script>const token=__TOKEN__;", text.index("def pickup_page"))
end = text.index("</script>", start) + len("</script>")
script = r'''<script>const token=__TOKEN__;let busy=false;let current=[];const bodies={};function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}function render(items){current=items.slice().reverse();const box=document.getElementById('mailbox');if(!current.length){box.innerHTML='<div class="empty">暂无邮件。</div>';return}box.innerHTML=current.map((m,i)=>'<article class="mail" onclick="openMessage('+i+')"><div class="subject">'+esc(m.subject||'(无主题)')+'</div><div class="meta">'+esc(m.from||'')+' · '+esc(m.date||'')+'</div><div class="body" id="body-'+i+'" style="display:none"></div></article>').join('');openMessage(0,true)}async function fetchMessages(force){const q=force?'?force=1':'';const r=await fetch('/pickup/'+encodeURIComponent(token)+'/messages'+q,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'读取失败');return d}async function openMessage(i,auto){const m=current[i];if(!m||!m.id)return;const el=document.getElementById('body-'+i);if(!el)return;if(el.style.display==='block'&&!auto){el.style.display='none';return}el.style.display='block';if(bodies[m.id]){el.textContent=bodies[m.id];return}el.textContent='正在打开邮件...';for(let n=0;n<20;n++){try{const r=await fetch('/pickup/'+encodeURIComponent(token)+'/message/'+encodeURIComponent(m.id),{cache:'no-store'});const d=await r.json();if(r.ok&&d.ready){const body=(d.message&&d.message.body)||'(无正文内容)';bodies[m.id]=body;el.textContent=body;return}if(r.status===404){el.textContent=d.error||'邮件不存在';return}}catch(e){}await new Promise(r=>setTimeout(r,1000))}el.textContent='正文读取较慢，请点击邮件重试。'}async function load(){if(busy)return;busy=true;const status=document.getElementById('status');try{let d=await fetchMessages(true);render(d.emails||[]);status.textContent=d.refreshing?'正在同步最新邮件...':'刚刚刷新';if(d.refreshing){for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,1000));d=await fetchMessages(false);if(!d.refreshing){render(d.emails||[]);status.textContent='最新邮件已显示';break}}}}catch(e){status.textContent='读取失败';if(!document.querySelector('.mail'))document.getElementById('mailbox').innerHTML='<div class="error">读取失败，稍后自动重试。</div>'}finally{busy=false}}load();setInterval(load,15000);</script>'''
text = text[:start] + script + text[end:]
path.write_bytes(text.replace("\r\n", "\n").encode("utf-8"))
