from pathlib import Path


path = Path("web_ui.py")
text = path.read_text(encoding="utf-8")
text = text.replace(
    ".body{margin-top:12px;padding:14px;background:#f5f8fa;color:#344c5c}.code-label{font-size:12px;color:#78909f;margin-bottom:4px}.code{font:700 34px/1.2 ui-monospace,Consolas,monospace;color:#132f40;letter-spacing:4px;padding:4px 0 12px}.message-text{white-space:pre-wrap;word-break:break-word;font-size:14px;line-height:1.7;color:#526b7a;border-top:1px solid #dce5ea;padding-top:10px}",
    ".body{margin-top:12px;background:#fff;color:#344c5c}.mail-frame{display:block;width:100%;height:520px;border:1px solid #dce5ea;background:#fff}.message-text{white-space:pre-wrap;word-break:break-word;font-size:14px;line-height:1.7;color:#526b7a;padding:14px;background:#f5f8fa}",
    1,
)

start = text.index("<script>const token=__TOKEN__;", text.index("def pickup_page"))
end = text.index("</script>", start) + len("</script>")
script = r'''<script>const token=__TOKEN__;let busy=false;let current=[];const bodies={};function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}function showBody(el,data){el.innerHTML='';if(data.html){const frame=document.createElement('iframe');frame.className='mail-frame';frame.setAttribute('sandbox','allow-same-origin');frame.setAttribute('referrerpolicy','no-referrer');const csp='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data: cid:; style-src \'unsafe-inline\'">';frame.srcdoc=csp+data.html;frame.onload=function(){try{frame.style.height=Math.min(Math.max(frame.contentDocument.documentElement.scrollHeight+24,240),1600)+'px'}catch(e){}};el.appendChild(frame)}else{const div=document.createElement('div');div.className='message-text';div.textContent=data.body||'(无正文内容)';el.appendChild(div)}}function render(items){current=items.slice().reverse();const box=document.getElementById('mailbox');if(!current.length){box.innerHTML='<div class="empty">暂无邮件。</div>';return}box.innerHTML=current.map((m,i)=>'<article class="mail" onclick="openMessage('+i+')"><div class="subject">'+esc(m.subject||'(无主题)')+'</div><div class="meta">'+esc(m.from||'')+' · '+esc(m.date||'')+'</div><div class="body" id="body-'+i+'" style="display:none"></div></article>').join('');openMessage(0,true)}async function fetchMessages(force){const q=force?'?force=1':'';const r=await fetch('/pickup/'+encodeURIComponent(token)+'/messages'+q,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'读取失败');return d}async function openMessage(i,auto){const m=current[i];if(!m||!m.id)return;const el=document.getElementById('body-'+i);if(!el)return;if(el.style.display==='block'&&!auto){el.style.display='none';return}el.style.display='block';if(bodies[m.id]){showBody(el,bodies[m.id]);return}el.textContent='正在打开邮件...';for(let n=0;n<20;n++){try{const r=await fetch('/pickup/'+encodeURIComponent(token)+'/message/'+encodeURIComponent(m.id),{cache:'no-store'});const d=await r.json();if(r.ok&&d.ready){const data=d.message||{};bodies[m.id]=data;showBody(el,data);return}if(r.status===404){el.textContent=d.error||'邮件不存在';return}}catch(e){}await new Promise(r=>setTimeout(r,1000))}el.textContent='正文读取较慢，请点击邮件重试。'}async function load(){if(busy)return;busy=true;const status=document.getElementById('status');try{let d=await fetchMessages(true);render(d.emails||[]);status.textContent=d.refreshing?'正在同步最新邮件...':'刚刚刷新';if(d.refreshing){for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,1000));d=await fetchMessages(false);if(!d.refreshing){render(d.emails||[]);status.textContent='最新邮件已显示';break}}}}catch(e){status.textContent='读取失败';if(!document.querySelector('.mail'))document.getElementById('mailbox').innerHTML='<div class="error">读取失败，稍后自动重试。</div>'}finally{busy=false}}load();setInterval(load,15000);</script>'''
text = text[:start] + script + text[end:]
path.write_bytes(text.replace("\r\n", "\n").encode("utf-8"))
